// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: consts.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountType 该结构与consts结构一样，客户端服务器共用，只要定义就不能改变
type AccountType int32

const (
	AccountType_DeviceId AccountType = 0
	AccountType_WX       AccountType = 1
	AccountType_FB       AccountType = 2
	AccountType_Git      AccountType = 3
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "DeviceId",
		1: "WX",
		2: "FB",
		3: "Git",
	}
	AccountType_value = map[string]int32{
		"DeviceId": 0,
		"WX":       1,
		"FB":       2,
		"Git":      3,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{0}
}

// RoleType 角色
type RoleType int32

const (
	RoleType_Mage     RoleType = 0
	RoleType_Warrior  RoleType = 1
	RoleType_Archer   RoleType = 2
	RoleType_Assassin RoleType = 3
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "Mage",
		1: "Warrior",
		2: "Archer",
		3: "Assassin",
	}
	RoleType_value = map[string]int32{
		"Mage":     0,
		"Warrior":  1,
		"Archer":   2,
		"Assassin": 3,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[1].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[1]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{1}
}

// GameState 游戏内状态和游戏外状态
type GameState int32

const (
	GameState_Idle    GameState = 0
	GameState_OutGame GameState = 1
	GameState_InGame  GameState = 2
	GameState_Logout  GameState = 3
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "Idle",
		1: "OutGame",
		2: "InGame",
		3: "Logout",
	}
	GameState_value = map[string]int32{
		"Idle":    0,
		"OutGame": 1,
		"InGame":  2,
		"Logout":  3,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[2].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[2]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{2}
}

// ItemType 道具类型
type ItemType int32

const (
	ItemType_Coin ItemType = 0
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "Coin",
	}
	ItemType_value = map[string]int32{
		"Coin": 0,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[3].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[3]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{3}
}

type NpcType int32

const (
	NpcType_Talk     NpcType = 0
	NpcType_Traverse NpcType = 1
)

// Enum value maps for NpcType.
var (
	NpcType_name = map[int32]string{
		0: "Talk",
		1: "Traverse",
	}
	NpcType_value = map[string]int32{
		"Talk":     0,
		"Traverse": 1,
	}
)

func (x NpcType) Enum() *NpcType {
	p := new(NpcType)
	*p = x
	return p
}

func (x NpcType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NpcType) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[4].Descriptor()
}

func (NpcType) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[4]
}

func (x NpcType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NpcType.Descriptor instead.
func (NpcType) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{4}
}

// NpcState npc状态
type NpcState int32

const (
	NpcState_ALIVE NpcState = 0
	NpcState_DIE   NpcState = 1
)

// Enum value maps for NpcState.
var (
	NpcState_name = map[int32]string{
		0: "ALIVE",
		1: "DIE",
	}
	NpcState_value = map[string]int32{
		"ALIVE": 0,
		"DIE":   1,
	}
)

func (x NpcState) Enum() *NpcState {
	p := new(NpcState)
	*p = x
	return p
}

func (x NpcState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NpcState) Descriptor() protoreflect.EnumDescriptor {
	return file_consts_proto_enumTypes[5].Descriptor()
}

func (NpcState) Type() protoreflect.EnumType {
	return &file_consts_proto_enumTypes[5]
}

func (x NpcState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NpcState.Descriptor instead.
func (NpcState) EnumDescriptor() ([]byte, []int) {
	return file_consts_proto_rawDescGZIP(), []int{5}
}

var File_consts_proto protoreflect.FileDescriptor

var file_consts_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x34, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x57, 0x58, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x42,
	0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x69, 0x74, 0x10, 0x03, 0x2a, 0x3b, 0x0a, 0x08, 0x52,
	0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x67, 0x65, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x61, 0x72, 0x72, 0x69, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x72, 0x63, 0x68, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x73,
	0x73, 0x61, 0x73, 0x73, 0x69, 0x6e, 0x10, 0x03, 0x2a, 0x3a, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x64, 0x6c, 0x65, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x6f,
	0x75, 0x74, 0x10, 0x03, 0x2a, 0x14, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x10, 0x00, 0x2a, 0x21, 0x0a, 0x07, 0x4e, 0x70,
	0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x61, 0x6c, 0x6b, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x76, 0x65, 0x72, 0x73, 0x65, 0x10, 0x01, 0x2a, 0x1e, 0x0a,
	0x08, 0x4e, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4c, 0x49,
	0x56, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x49, 0x45, 0x10, 0x01, 0x42, 0x08, 0x5a,
	0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consts_proto_rawDescOnce sync.Once
	file_consts_proto_rawDescData = file_consts_proto_rawDesc
)

func file_consts_proto_rawDescGZIP() []byte {
	file_consts_proto_rawDescOnce.Do(func() {
		file_consts_proto_rawDescData = protoimpl.X.CompressGZIP(file_consts_proto_rawDescData)
	})
	return file_consts_proto_rawDescData
}

var file_consts_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_consts_proto_goTypes = []interface{}{
	(AccountType)(0), // 0: proto.AccountType
	(RoleType)(0),    // 1: proto.RoleType
	(GameState)(0),   // 2: proto.GameState
	(ItemType)(0),    // 3: proto.ItemType
	(NpcType)(0),     // 4: proto.NpcType
	(NpcState)(0),    // 5: proto.NpcState
}
var file_consts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_consts_proto_init() }
func file_consts_proto_init() {
	if File_consts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consts_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consts_proto_goTypes,
		DependencyIndexes: file_consts_proto_depIdxs,
		EnumInfos:         file_consts_proto_enumTypes,
	}.Build()
	File_consts_proto = out.File
	file_consts_proto_rawDesc = nil
	file_consts_proto_goTypes = nil
	file_consts_proto_depIdxs = nil
}
